In [1]:
import pandas as pd

In [52]:
df = pd.read_csv('abc.csv')
#df=df.drop(columns=['Unnamed: 0'])

In [56]:
df

        Latitude   Longitude   Altitude   Velocity   Time
0          -13594       -9455         27         82      0
1          -13925       -9255         71         82      4
2          -14265       -9055        117         84      8
3          -14615       -8853        163         86     13
4          -14974       -8651        207         88     17
...           ...         ...        ...        ...    ...
328114     -11885       -7532         80         72    934
328115     -12046       -7840         62         72    938
328116     -12208       -8147         43         72    943
328117     -12374       -8447         27         72    948
328118     -12541       -8743         14         72    952

[328119 rows x 5 columns]

In [54]:
type(df['Time '][0])

numpy.int64

In [10]:
df.columns

Index(['Latitude ', 'Longitude ', 'Altitude ', 'Velocity ', 'Time '], dtype='object')

In [6]:
df['Time']

KeyError: 'Time'

In [17]:
l = []
cnt = 0
for index, row in df.iterrows():
    if row['Time '] == 0:
        cnt += 1
        l.append(cnt)
    else: 
        l.append(cnt)

In [22]:
l[0]

1

In [112]:
df1 = pd.read_csv('abc2.csv')

In [111]:
df1

        Plane Number  Latitude   Longitude   Altitude   Velocity   Time
0                  0     -13594       -9455         27         82      0
1                  0     -13925       -9255         71         82      4
2                  0     -14265       -9055        117         84      8
3                  0     -14615       -8853        163         86     13
4                  0     -14974       -8651        207         88     17
...              ...        ...         ...        ...        ...    ...
328114          2128     -11885       -7532         80         72    934
328115          2128     -12046       -7840         62         72    938
328116          2128     -12208       -8147         43         72    943
328117          2128     -12374       -8447         27         72    948
328118          2128     -12541       -8743         14         72    952

[328119 rows x 6 columns]

In [161]:
l2 = []
v = 0
cnt = 0
for index, row in df.iterrows():
    if row['Time '] == 0:
        if cnt != 0: 
            l2.append((round(v/cnt, 2)))
        cnt = 1
        v = row['Velocity ']
    else: 
        cnt += 1
        v += row['Velocity ']
        
        
l2.append(round(v/cnt, 2))

In [155]:
l = []
l1 = []
v = 0
cnt = 0
for index, row in df.iterrows():
    if row['Time '] == 0:
        if v != 0 and cnt != 0:
            l.append(v)
            l1.append(cnt)
        v = row['Velocity ']
        cnt = 1
    else:
        cnt += 1
        v = max(v, row['Velocity '])
        
l.append(v)
l1.append(cnt)

In [148]:
len(l)

2129

In [81]:
lavg = []
lmax = []
for i in range (0, len(l1)):
    for j in range(0, l1[i]):
        lavg.append(l2[i])
        lmax.append(l[i])

In [82]:
df

        Latitude   Longitude   Altitude   Velocity   Time
0          -13594       -9455         27         82      0
1          -13925       -9255         71         82      4
2          -14265       -9055        117         84      8
3          -14615       -8853        163         86     13
4          -14974       -8651        207         88     17
...           ...         ...        ...        ...    ...
328114     -11885       -7532         80         72    934
328115     -12046       -7840         62         72    938
328116     -12208       -8147         43         72    943
328117     -12374       -8447         27         72    948
328118     -12541       -8743         14         72    952

[328119 rows x 5 columns]

In [83]:
df['Average Speed'] = lavg

In [84]:
df['Max Speed'] = lmax

In [85]:
df

,Latitude,Longitude,Altitude,Velocity,Time,Average Speed,Max Speed
0,-13594,-9455,27,82,0,163.73,217
1,-13925,-9255,71,82,4,163.73,217
2,-14265,-9055,117,84,8,163.73,217
3,-14615,-8853,163,86,13,163.73,217
4,-14974,-8651,207,88,17,163.73,217
...,...,...,...,...,...,...,...
328114,-11885,-7532,80,72,934,103.64,140
328115,-12046,-7840,62,72,938,103.64,140
328116,-12208,-8147,43,72,943,103.64,140
328117,-12374,-8447,27,72,948,103.64,140
328118,-12541,-8743,14,72,952,103.64,140

In [86]:
df.to_csv('sihfinalpreprocess.csv')

In [87]:
df1 = pd.DataFrame()

In [88]:
df1['Average Speed'] = l2

In [93]:
df1['Max Speed'] = l

In [113]:
df1

        Plane Number  Latitude   Longitude   Altitude   Velocity   Time
0                  0     -13594       -9455         27         82      0
1                  0     -13925       -9255         71         82      4
2                  0     -14265       -9055        117         84      8
3                  0     -14615       -8853        163         86     13
4                  0     -14974       -8651        207         88     17
...              ...        ...         ...        ...        ...    ...
328114          2128     -11885       -7532         80         72    934
328115          2128     -12046       -7840         62         72    938
328116          2128     -12208       -8147         43         72    943
328117          2128     -12374       -8447         27         72    948
328118          2128     -12541       -8743         14         72    952

[328119 rows x 6 columns]

In [115]:
df1.to_csv('AeroplaneClusterring.csv')

In [116]:
df3 = pd.read_csv('AeroplaneClusterring.csv')

In [117]:
df3

,Unnamed: 0,Plane Number,Latitude,Longitude,Altitude,Velocity,Time
0,0,0,-13594,-9455,27,82,0
1,1,0,-13925,-9255,71,82,4
2,2,0,-14265,-9055,117,84,8
3,3,0,-14615,-8853,163,86,13
4,4,0,-14974,-8651,207,88,17
...,...,...,...,...,...,...,...
328114,328114,2128,-11885,-7532,80,72,934
328115,328115,2128,-12046,-7840,62,72,938
328116,328116,2128,-12208,-8147,43,72,943
328117,328117,2128,-12374,-8447,27,72,948
328118,328118,2128,-12541,-8743,14,72,952

In [118]:
df4 = pd.read_csv('missile dataset csv.csv')

In [119]:
df4

      Plane Number   Latitude  Longitude   Altitude  Velocity       Time
0               0_   2236.595   2234.830   1842.848  5340.013   1.020000
1               0_   5549.703   5073.689   4992.230  5214.717   2.039999
2               0_   8862.811   7912.556   7923.322  5095.332   3.059998
3               0_  12175.920  10751.420  10636.120  4982.282   4.079997
4               0_  15489.030  13590.290  13130.630  4876.010   5.099996
...            ...        ...        ...        ...       ...        ...
51032         999_  67402.930  67067.570  10876.470  4536.389  23.460350
51033         999_  70364.910  70013.220   8775.216  4632.458  24.480370
51034         999_  73326.900  72958.870   6455.668  4736.255  25.500390
51035         999_  76288.880  75904.520   3917.830  4847.284  26.520420
51036         999_  79250.870  78850.160   1161.700  4965.060  27.540440

[51037 rows x 6 columns]

In [125]:
avgmissile = []
maxmissile = []
v = 0
v1 = 0
cnt = 0
temp = ""
for index, row in df4.iterrows():
    if row['Plane Number'] != temp:
        if cnt != 0: 
            avgmissile.append((round(v/cnt, 2)))
            maxmissile.append(v1)
        cnt = 1
        v = row['Velocity']
        v1 = row['Velocity']
        temp = row['Plane Number']
    else: 
        cnt += 1
        v += row['Velocity']
        temp = row['Plane Number']
        v1 = max(v1, row['Velocity'])
        
        
avgmissile.append(round(v/cnt, 2))

In [129]:
maxmissile.append(v1)

In [130]:
len(maxmissile)

2000

In [119]:
type(row['Plane Number'])

str

In [124]:
avgmissile

[4673.66,
 4799.6,
 4712.09,
 4468.89,
 4743.94,
 4791.36,
 4794.23,
 4600.77,
 4665.5,
 5133.49,
 4523.11,
 4832.47,
 4454.65,
 4840.51,
 4559.81,
 4706.96,
 4687.46,
 4737.24,
 4650.0,
 4596.17,
 4322.99,
 4419.67,
 4770.74,
 4391.44,
 4783.89,
 4616.86,
 4540.46,
 4570.96,
 4848.27,
 4504.95,
 4631.51,
 4996.03,
 4881.9,
 4903.18,
 4480.56,
 4542.95,
 4624.38,
 5043.98,
 4527.2,
 4674.65,
 4730.13,
 4649.91,
 4785.71,
 4795.71,
 4435.83,
 4952.06,
 4884.84,
 4583.71,
 4858.09,
 4863.44,
 5015.48,
 4494.29,
 4746.49,
 4711.85,
 4949.14,
 4698.38,
 4662.09,
 4858.51,
 4594.88,
 4604.47,
 4649.85,
 4741.96,
 5278.1,
 5080.51,
 4618.84,
 4322.39,
 4536.87,
 4373.95,
 4765.69,
 4887.94,
 5080.18,
 4557.48,
 4605.69,
 4812.27,
 4556.71,
 4702.83,
 4615.63,
 4566.08,
 4915.67,
 4973.35,
 4358.94,
 4889.4,
 4558.88,
 4764.79,
 4844.14,
 4609.33,
 4563.85,
 4377.96,
 4567.66,
 5013.96,
 4939.26,
 4852.32,
 4574.24,
 4734.66,
 4885.05,
 4444.69,
 4700.2,
 4898.77,
 4347.71,
 4514.66,
 4847.12,
 4697.32,
 4678.79,
 4333.65,
 4951.49,
 5111.93,
 4898.43,
 4305.74,
 4738.74,
 4776.38,
 4644.99,
 4414.09,
 5172.6,
 4348.56,
 4598.4,
 4982.4,
 4572.04,
 4617.74,
 4959.74,
 4460.44,
 4709.02,
 5234.25,
 4476.22,
 4939.62,
 4368.24,
 4842.87,
 4443.46,
 4674.99,
 4605.18,
 5237.04,
 4873.85,
 4686.09,
 4647.94,
 5135.65,
 4455.23,
 4514.75,
 4624.13,
 4417.06,
 4621.61,
 5009.4,
 4578.42,
 4793.33,
 5031.42,
 4785.41,
 4665.61,
 4818.86,
 4772.28,
 4512.15,
 4785.23,
 4829.28,
 4917.07,
 5092.91,
 4277.74,
 5001.54,
 4789.18,
 4674.2,
 4651.89,
 4661.62,
 5099.82,
 4830.07,
 4500.66,
 4756.79,
 4709.69,
 4697.44,
 4559.58,
 4824.96,
 4812.69,
 4913.09,
 4684.05,
 4751.59,
 4618.38,
 4433.46,
 4588.24,
 4745.88,
 4461.46,
 4655.86,
 4579.21,
 4705.35,
 4525.91,
 4897.2,
 4732.85,
 4744.39,
 4496.59,
 4734.23,
 4739.45,
 4687.36,
 4800.14,
 4346.86,
 5050.34,
 4586.94,
 4951.75,
 4665.31,
 4998.14,
 4908.67,
 5199.42,
 4232.06,
 4526.59,
 4641.38,
 5291.7,
 4732.08,
 4728.73,
 4423.26,
 4537.04,
 4648.19,
 4514.69,
 4844.29,
 4746.82,
 4500.41,
 4605.21,
 4892.0,
 4620.36,
 4833.14,
 4748.3,
 4616.58,
 4509.62,
 4995.38,
 5179.2,
 4650.52,
 4555.66,
 4911.32,
 4601.14,
 4511.9,
 4567.49,
 4580.15,
 4866.3,
 4538.84,
 4343.42,
 5027.98,
 4564.27,
 4423.08,
 4544.31,
 4491.16,
 4698.99,
 4749.17,
 4766.01,
 4541.5,
 4358.2,
 4942.2,
 4640.99,
 4748.05,
 4337.3,
 4916.67,
 4475.92,
 4567.88,
 4755.79,
 4413.16,
 4404.27,
 4242.19,
 4594.01,
 4680.71,
 4870.7,
 4915.4,
 4702.38,
 4845.01,
 4852.37,
 4395.69,
 5062.53,
 4894.63,
 4806.86,
 4802.4,
 4832.41,
 4766.86,
 4453.48,
 4920.29,
 4948.03,
 4930.85,
 4757.5,
 4602.49,
 4693.86,
 4785.87,
 4796.96,
 4481.88,
 4600.32,
 4777.79,
 4660.74,
 4706.76,
 4985.0,
 4957.92,
 4500.03,
 4831.12,
 4791.82,
 4685.0,
 4559.46,
 4726.54,
 4627.44,
 4954.83,
 4539.82,
 4920.07,
 4456.38,
 4793.84,
 4455.38,
 4707.66,
 4986.96,
 4621.95,
 4727.97,
 4800.06,
 4954.15,
 5061.03,
 4594.39,
 4464.57,
 4628.53,
 5181.0,
 4589.95,
 4934.54,
 4523.83,
 4355.62,
 4585.3,
 4723.62,
 4952.12,
 4458.85,
 4757.85,
 4519.53,
 4941.96,
 5061.04,
 4465.28,
 4892.91,
 4259.16,
 5009.12,
 4705.72,
 4857.05,
 4675.63,
 4694.1,
 4237.49,
 5072.19,
 4388.73,
 4587.78,
 4897.11,
 4888.65,
 4799.59,
 4890.75,
 4634.35,
 4501.9,
 5120.59,
 4957.98,
 4778.64,
 4738.52,
 4652.53,
 4594.53,
 4929.56,
 4445.77,
 4581.16,
 4785.96,
 4884.38,
 4616.98,
 4768.31,
 4877.23,
 4438.47,
 4486.69,
 4757.41,
 4634.34,
 4650.63,
 4807.4,
 4747.11,
 4780.08,
 4467.91,
 4842.45,
 4941.6,
 4905.71,
 4720.34,
 4717.19,
 4496.64,
 5067.67,
 4669.01,
 5021.88,
 4802.09,
 4276.55,
 4912.73,
 4682.19,
 4975.05,
 5014.31,
 5272.92,
 4555.55,
 4688.03,
 4663.21,
 4470.47,
 4673.64,
 4263.2,
 4954.32,
 4877.71,
 4693.11,
 4687.99,
 4640.05,
 4966.45,
 5095.47,
 4853.49,
 4645.41,
 4976.65,
 4403.22,
 5069.02,
 4905.38,
 4549.06,
 4798.77,
 5072.52,
 5079.24,
 4456.52,
 4859.28,
 4680.8,
 4711.37,
 4790.44,
 4943.51,
 4310.37,
 4871.3,
 4857.05,
 4798.17,
 4396.73,
 4584.34,
 4301.29,
 4603.55,
 4813.41,
 4693.19,
 4784.7,
 4934.12,
 4733.1,
 4565.07,
 4463.99,
 4558.51,
 4625.54,
 4688.91,
 4362.83,
 5004.76,
 5176.76,
 4694.95,
 4494.06,
 4703.89,
 4619.21,
 4623.5,
 4868.46,
 4936.9,
 4540.4,
 5022.84,
 4428.57,
 4765.6,
 4863.02,
 5235.06,
 4514.9,
 4751.16,
 4601.89,
 4689.21,
 4859.25,
 4283.57,
 4727.07,
 4378.48,
 4724.3,
 4595.66,
 4771.26,
 4372.52,
 4742.32,
 4942.86,
 4610.14,
 4561.86,
 4800.11,
 5104.64,
 4582.75,
 4713.46,
 4441.26,
 4371.42,
 4707.24,
 4812.2,
 4516.03,
 4985.12,
 4738.28,
 4428.01,
 4594.98,
 4579.54,
 4987.39,
 4484.93,
 4391.38,
 4840.56,
 5080.09,
 4827.43,
 4674.63,
 4841.74,
 4564.96,
 4623.56,
 4494.45,
 4619.65,
 4713.0,
 4499.8,
 4438.32,
 4770.37,
 4902.9,
 4601.32,
 4695.97,
 5081.86,
 4847.06,
 4693.27,
 4663.64,
 4790.56,
 5066.69,
 4937.2,
 4625.98,
 4850.23,
 4928.57,
 4994.92,
 4955.39,
 4852.72,
 4651.76,
 4856.17,
 4815.07,
 4618.77,
 4408.24,
 4866.78,
 4545.93,
 5233.09,
 4322.33,
 5103.13,
 4552.75,
 4838.23,
 4662.07,
 4634.01,
 4935.55,
 5105.93,
 4812.65,
 4716.96,
 4672.24,
 5086.97,
 4743.37,
 4677.15,
 4433.8,
 4978.96,
 4615.88,
 4314.94,
 4870.47,
 4622.09,
 4612.68,
 4743.53,
 4954.47,
 4750.17,
 4766.64,
 4821.4,
 5101.8,
 4812.5,
 4426.81,
 4755.45,
 4475.93,
 4355.57,
 4724.23,
 4706.71,
 4819.55,
 5018.3,
 4433.65,
 4939.36,
 4704.79,
 4610.4,
 4998.07,
 4804.68,
 4806.29,
 4289.48,
 4585.63,
 4835.29,
 4556.47,
 4445.73,
 4697.77,
 4948.6,
 4715.85,
 4971.99,
 4281.61,
 4382.78,
 4564.4,
 4708.4,
 4681.28,
 4785.48,
 4988.89,
 4823.57,
 4695.98,
 5208.21,
 4873.5,
 4683.04,
 4660.2,
 4623.15,
 4977.54,
 4630.0,
 4756.96,
 4586.26,
 4801.61,
 4723.64,
 4828.92,
 5040.43,
 4533.91,
 4649.75,
 4679.07,
 4650.14,
 4979.65,
 4518.33,
 4704.7,
 4607.87,
 4891.51,
 4642.27,
 4569.95,
 4695.86,
 4650.04,
 4510.91,
 4316.01,
 4905.26,
 4637.5,
 4674.42,
 4389.11,
 4675.44,
 4726.01,
 4565.79,
 4450.56,
 4943.62,
 4576.38,
 4730.94,
 4481.51,
 4629.34,
 4856.74,
 4482.96,
 4949.53,
 4536.39,
 4606.39,
 4918.67,
 4656.96,
 4492.89,
 4602.36,
 4822.2,
 4563.66,
 4461.0,
 4639.72,
 4428.48,
 4301.02,
 4605.03,
 4418.27,
 4529.38,
 4831.0,
 4959.12,
 4764.26,
 4552.05,
 4492.97,
 4638.68,
 4294.51,
 4675.76,
 4866.42,
 4608.09,
 4508.12,
 4900.21,
 4723.46,
 4727.08,
 4782.98,
 4583.31,
 4982.89,
 4475.64,
 4991.36,
 4644.17,
 4648.9,
 4601.09,
 4801.96,
 4786.58,
 4509.71,
 4755.61,
 4768.75,
 5111.58,
 4767.82,
 4601.6,
 4732.3,
 4713.76,
 4387.69,
 4371.47,
 5084.22,
 4837.11,
 4500.91,
 4776.85,
 4923.6,
 4693.71,
 4550.56,
 4523.06,
 4895.71,
 4454.17,
 4574.69,
 4225.21,
 4717.14,
 4851.8,
 4688.52,
 4427.25,
 4528.39,
 4697.4,
 4707.5,
 4575.04,
 4554.32,
 4800.35,
 4738.49,
 4628.23,
 4493.53,
 5066.73,
 4615.64,
 4699.43,
 4795.24,
 4679.17,
 4492.55,
 4663.2,
 4440.16,
 4419.27,
 4749.88,
 4450.13,
 4977.42,
 4918.59,
 5074.5,
 4541.98,
 4680.27,
 4553.05,
 4633.92,
 4794.73,
 4667.23,
 5036.64,
 4602.94,
 4652.99,
 4626.44,
 4696.45,
 4594.02,
 4782.95,
 4322.72,
 4516.27,
 4605.74,
 4684.53,
 4703.61,
 4743.78,
 4572.35,
 4722.98,
 5066.23,
 4624.34,
 4395.89,
 4795.6,
 4478.08,
 4741.69,
 4415.0,
 4441.37,
 4766.37,
 4607.76,
 4983.12,
 4586.59,
 4953.25,
 4941.33,
 5182.64,
 4269.4,
 4921.51,
 4838.94,
 4486.76,
 4942.61,
 4907.74,
 4425.37,
 4852.75,
 4420.17,
 5004.7,
 4923.1,
 4670.1,
 4720.1,
 4986.52,
 4592.05,
 4398.06,
 4737.83,
 4623.55,
 5003.54,
 4486.94,
 4537.29,
 4310.12,
 4466.41,
 4535.07,
 4889.39,
 4666.12,
 4634.96,
 4561.93,
 4788.36,
 4546.47,
 4884.14,
 4528.2,
 4972.38,
 5021.61,
 4411.49,
 5060.3,
 4445.65,
 4674.21,
 5037.75,
 4975.83,
 4670.19,
 4860.56,
 4312.74,
 5005.45,
 4388.49,
 4304.54,
 4879.58,
 4366.35,
 4532.76,
 4262.92,
 4562.2,
 4383.93,
 4811.57,
 4464.8,
 4539.62,
 5138.8,
 4834.17,
 4778.41,
 4284.29,
 4795.91,
 5107.73,
 4695.53,
 4543.99,
 4479.86,
 4595.41,
 4745.99,
 4589.13,
 4507.1,
 4951.12,
 4630.65,
 4637.87,
 4627.97,
 4680.54,
 4746.09,
 4958.77,
 4881.67,
 4600.59,
 4663.0,
 4522.68,
 4830.11,
 4550.42,
 4591.46,
 4906.97,
 4855.7,
 4824.92,
 4517.43,
 4960.39,
 4781.37,
 4886.53,
 4821.53,
 4400.7,
 4824.06,
 4524.24,
 4963.47,
 4915.15,
 4815.11,
 4702.28,
 4605.04,
 4855.24,
 4939.94,
 4822.84,
 4818.25,
 4671.67,
 4682.91,
 4932.92,
 4937.82,
 4255.55,
 4749.77,
 4636.2,
 4652.54,
 4732.98,
 4929.49,
 4731.22,
 4677.03,
 4917.48,
 4699.78,
 4623.31,
 4938.91,
 4750.45,
 4649.86,
 4840.98,
 4508.63,
 5112.55,
 4409.06,
 4748.84,
 5137.14,
 4448.3,
 4835.08,
 4840.53,
 5002.33,
 4575.77,
 4864.05,
 4714.82,
 4666.71,
 4471.57,
 4571.91,
 5010.36,
 4781.45,
 5117.0,
 4876.13,
 4245.24,
 4895.79,
 4686.79,
 4669.18,
 4662.07,
 4821.7,
 4606.2,
 4772.7,
 4723.28,
 4806.84,
 5061.57,
 4632.46,
 4701.09,
 4602.82,
 4693.92,
 4852.24,
 4554.84,
 5078.66,
 4382.09,
 4767.34,
 4235.0,
 4620.36,
 4696.1,
 4419.22,
 4680.09,
 4940.8,
 4834.89,
 4703.97,
 5168.96,
 4770.65,
 5087.18,
 4842.32,
 4486.4,
 4795.8,
 4640.97,
 4851.73,
 4812.42,
 4480.31,
 4549.09,
 4670.63,
 4783.42,
 4894.41,
 4692.43,
 4943.59,
 4514.68,
 4635.04,
 4634.09,
 4621.86,
 4550.94,
 5011.96,
 4402.22,
 4996.9,
 4528.92,
 4892.77,
 5041.05,
 4609.77,
 4705.73,
 4583.48,
 4923.23,
 4623.63,
 4766.21,
 4404.42,
 4904.14,
 4745.19,
 4540.85,
 4477.13,
 4996.48,
 4340.72,
 4650.99,
 5036.05,
 4459.89,
 4553.63,
 4533.65,
 4926.08,
 4912.04,
 4706.79,
 4545.66,
 4839.65,
 5018.81,
 4897.53,
 4786.02,
 4948.54,
 5090.18,
 4852.74,
 4785.1,
 4964.84,
 4744.42,
 4969.67,
 4796.75,
 4552.33,
 4712.98,
 4484.22,
 4438.42,
 4753.18,
 4538.93,
 4864.48,
 4619.99,
 4842.63,
 4856.24,
 4658.22,
 4287.42,
 4900.1,
 4158.75,
 4818.92,
 4880.27,
 4828.23,
 4987.99,
 4537.88,
 4698.43,
 4758.67,
 4806.68,
 4260.22,
 4487.67,
 4753.09,
 4788.46,
 4953.51,
 4721.16,
 4691.74,
 4729.84,
 4454.85,
 4507.9,
 5023.0,
 4971.85,
 4835.11,
 5044.82,
 4264.91,
 4241.29,
 ...]

In [131]:
df3

        Id  Average Speed  Max Speed
0        0         163.73        217
1        1         128.43        180
2        2          47.17         50
3        3         111.94        157
4        4          38.77         50
...    ...            ...        ...
2124  2124         123.28        149
2125  2125         165.62        242
2126  2126         126.59        169
2127  2127         163.56        229
2128  2128         103.64        140

[2129 rows x 3 columns]

In [132]:
print(l,l2)

[217, 180, 50, 157, 50, 162, 236, 46, 177, 177, 62, 45, 48, 221, 53, 209, 211, 171, 50, 225, 138, 120, 98, 194, 149, 118, 55, 188, 83, 228, 223, 210, 57, 223, 79, 143, 160, 221, 45, 199, 94, 224, 218, 47, 53, 221, 77, 38, 73, 210, 139, 52, 173, 64, 178, 160, 115, 66, 51, 64, 71, 160, 69, 170, 64, 78, 125, 198, 103, 57, 59, 104, 56, 48, 34, 49, 30, 108, 57, 42, 57, 49, 42, 198, 48, 204, 63, 157, 143, 100, 107, 54, 48, 44, 187, 158, 163, 35, 149, 53, 66, 59, 71, 57, 40, 59, 53, 73, 194, 69, 67, 75, 60, 75, 155, 78, 82, 165, 82, 53, 120, 194, 63, 212, 207, 63, 210, 183, 210, 223, 209, 73, 216, 191, 11, 227, 227, 234, 64, 202, 210, 196, 219, 208, 153, 42, 184, 239, 213, 74, 191, 169, 213, 193, 212, 190, 151, 205, 234, 212, 214, 165, 144, 204, 159, 176, 141, 219, 205, 205, 55, 141, 199, 192, 180, 184, 137, 221, 213, 170, 200, 37, 178, 196, 193, 220, 216, 217, 219, 75, 216, 65, 192, 28, 34, 217, 143, 85, 206, 210, 169, 94, 136, 119, 67, 129, 213, 153, 219, 187, 75, 213, 121, 220, 173, 170, 199, 74, 88, 149, 145, 153, 210, 117, 192, 141, 146, 202, 141, 209, 64, 69, 156, 142, 187, 139, 194, 178, 228, 132, 189, 162, 232, 69, 87, 163, 163, 145, 190, 222, 147, 202, 218, 229, 146, 117, 83, 192, 210, 139, 186, 214, 82, 116, 191, 216, 158, 206, 199, 47, 60, 168, 204, 182, 59, 157, 149, 194, 79, 83, 216, 159, 99, 142, 220, 188, 199, 98, 160, 149, 74, 131, 64, 183, 142, 194, 129, 42, 227, 189, 190, 135, 23, 75, 224, 237, 102, 78, 197, 168, 58, 166, 121, 189, 73, 205, 69, 175, 156, 125, 176, 155, 170, 148, 184, 196, 80, 141, 150, 187, 191, 123, 140, 175, 181, 131, 132, 143, 159, 178, 138, 87, 146, 151, 237, 152, 141, 224, 163, 143, 166, 224, 170, 152, 152, 150, 195, 135, 145, 143, 196, 196, 187, 115, 47, 125, 68, 196, 87, 146, 41, 68, 235, 148, 109, 170, 155, 161, 149, 96, 157, 137, 171, 148, 129, 200, 143, 70, 72, 216, 170, 178, 162, 140, 136, 199, 151, 139, 188, 143, 243, 189, 142, 167, 148, 157, 225, 209, 44, 161, 140, 189, 145, 202, 177, 136, 153, 154, 145, 180, 229, 12, 181, 191, 69, 172, 82, 160, 143, 67, 122, 193, 40, 35, 124, 192, 130, 137, 147, 39, 150, 166, 128, 66, 155, 186, 144, 178, 81, 138, 94, 135, 177, 144, 143, 132, 160, 236, 55, 146, 147, 200, 183, 37, 204, 226, 130, 174, 206, 148, 67, 151, 193, 150, 202, 117, 188, 144, 164, 233, 161, 200, 195, 158, 142, 145, 126, 135, 121, 56, 142, 213, 191, 173, 46, 149, 129, 142, 127, 194, 162, 128, 146, 253, 133, 38, 183, 42, 136, 102, 134, 216, 136, 234, 194, 128, 171, 110, 130, 43, 187, 116, 192, 192, 60, 214, 134, 122, 125, 161, 211, 138, 132, 212, 220, 138, 139, 172, 136, 146, 93, 105, 129, 125, 220, 37, 132, 66, 163, 226, 139, 205, 138, 141, 178, 119, 195, 42, 163, 154, 146, 138, 189, 94, 177, 139, 138, 84, 174, 134, 153, 191, 153, 135, 166, 207, 42, 140, 140, 230, 69, 140, 135, 195, 119, 186, 149, 208, 134, 98, 137, 60, 217, 187, 138, 171, 120, 151, 158, 127, 147, 137, 152, 112, 220, 173, 158, 122, 137, 180, 175, 154, 164, 141, 74, 150, 176, 140, 140, 233, 134, 212, 114, 191, 116, 138, 198, 154, 138, 144, 198, 196, 130, 139, 167, 133, 139, 154, 153, 186, 138, 240, 126, 153, 33, 138, 140, 131, 175, 144, 180, 139, 79, 138, 177, 139, 130, 225, 192, 223, 146, 139, 234, 147, 232, 137, 190, 142, 136, 196, 169, 152, 124, 213, 135, 162, 138, 179, 142, 126, 243, 55, 116, 155, 135, 199, 190, 124, 130, 243, 233, 133, 205, 121, 199, 135, 205, 53, 130, 202, 137, 189, 163, 218, 139, 143, 215, 182, 211, 133, 197, 138, 203, 175, 73, 125, 196, 198, 168, 192, 136, 177, 134, 135, 205, 240, 130, 166, 135, 168, 204, 186, 140, 90, 212, 191, 134, 135, 196, 104, 211, 67, 110, 183, 214, 123, 174, 107, 201, 136, 176, 125, 201, 23, 200, 127, 139, 234, 137, 201, 92, 62, 135, 113, 233, 148, 226, 192, 164, 114, 130, 137, 200, 230, 136, 183, 57, 142, 148, 200, 139, 150, 68, 154, 166, 230, 160, 150, 225, 209, 96, 173, 196, 133, 229, 111, 139, 150, 159, 142, 172, 158, 72, 230, 125, 145, 153, 101, 229, 197, 156, 88, 147, 208, 132, 216, 151, 192, 230, 229, 144, 152, 61, 235, 134, 172, 232, 194, 168, 220, 191, 236, 85, 189, 58, 126, 135, 156, 70, 209, 253, 241, 143, 186, 212, 72, 173, 136, 202, 50, 228, 37, 142, 175, 51, 214, 199, 142, 243, 167, 158, 242, 95, 196, 249, 141, 142, 162, 47, 93, 164, 176, 149, 118, 235, 131, 135, 151, 218, 49, 182, 237, 142, 141, 239, 127, 129, 247, 192, 126, 164, 234, 62, 145, 134, 121, 214, 66, 71, 80, 166, 130, 127, 236, 141, 132, 131, 140, 158, 122, 168, 213, 199, 141, 98, 126, 176, 124, 157, 218, 156, 134, 151, 210, 129, 198, 150, 163, 148, 156, 236, 161, 155, 129, 147, 161, 215, 156, 135, 139, 251, 200, 155, 163, 215, 129, 68, 147, 214, 133, 160, 141, 146, 154, 78, 150, 249, 156, 140, 248, 118, 204, 141, 135, 154, 172, 127, 226, 168, 212, 136, 146, 127, 167, 189, 207, 166, 149, 143, 143, 233, 155, 146, 167, 156, 206, 137, 138, 144, 144, 157, 101, 69, 91, 162, 144, 235, 142, 191, 185, 102, 133, 150, 135, 142, 244, 138, 212, 140, 216, 78, 234, 103, 95, 138, 186, 140, 173, 134, 60, 161, 197, 129, 139, 65, 159, 92, 186, 213, 142, 76, 112, 137, 147, 199, 245, 109, 76, 160, 135, 149, 193, 80, 139, 209, 204, 150, 157, 68, 135, 163, 156, 236, 154, 134, 161, 202, 212, 145, 211, 147, 207, 141, 135, 142, 169, 156, 224, 189, 193, 189, 150, 146, 200, 135, 155, 195, 218, 185, 153, 147, 53, 198, 150, 151, 245, 147, 30, 122, 208, 141, 234, 209, 226, 146, 199, 185, 236, 145, 150, 195, 140, 72, 204, 145, 153, 209, 166, 217, 36, 158, 158, 69, 131, 214, 196, 133, 68, 150, 166, 163, 146, 131, 138, 191, 149, 144, 213, 211, 210, 127, 170, 141, 154, 47, 131, 202, 54, 217, 223, 185, 139, 218, 137, 164, 144, 121, 245, 148, 140, 177, 34, 150, 49, 58, 199, 128, 221, 207, 149, 150, 208, 123, 214, 242, 231, 77, 120, 118, 135, 217, 76, 161, 146, 170, 239, 133, 164, 204, 153, 133, 72, 221, 161, 240, 249, 131, 144, 132, 146, 165, 127, 44, 163, 52, 199, 49, 161, 147, 158, 245, 149, 156, 148, 211, 175, 61, 175, 73, 204, 158, 204, 151, 170, 162, 180, 120, 89, 154, 151, 160, 146, 66, 137, 148, 139, 12, 105, 72, 187, 156, 184, 48, 173, 182, 174, 231, 139, 165, 141, 65, 108, 156, 154, 103, 157, 100, 155, 159, 175, 132, 170, 140, 161, 159, 160, 214, 62, 167, 72, 212, 148, 211, 172, 152, 90, 187, 146, 151, 188, 154, 87, 210, 161, 221, 200, 143, 42, 189, 52, 228, 207, 134, 150, 211, 115, 51, 136, 154, 159, 130, 108, 225, 175, 234, 150, 164, 148, 111, 132, 224, 132, 141, 128, 227, 147, 199, 94, 145, 163, 150, 216, 157, 134, 135, 116, 231, 189, 118, 200, 129, 146, 130, 246, 160, 104, 145, 136, 153, 203, 107, 219, 143, 197, 206, 235, 139, 154, 73, 193, 156, 73, 230, 133, 184, 169, 235, 55, 138, 140, 92, 133, 237, 74, 132, 152, 190, 40, 149, 97, 205, 240, 126, 180, 242, 111, 148, 175, 242, 147, 186, 152, 142, 141, 213, 234, 148, 196, 199, 127, 159, 142, 149, 131, 182, 202, 209, 139, 179, 123, 128, 197, 126, 201, 161, 219, 128, 157, 182, 164, 144, 187, 144, 147, 186, 195, 143, 149, 168, 127, 144, 178, 152, 93, 181, 144, 197, 96, 161, 166, 150, 143, 215, 69, 92, 123, 142, 163, 141, 136, 155, 87, 133, 172, 131, 151, 142, 87, 142, 139, 143, 52, 155, 191, 69, 90, 86, 162, 210, 151, 158, 138, 197, 177, 175, 161, 134, 145, 165, 150, 139, 187, 216, 146, 122, 149, 161, 146, 144, 79, 145, 164, 215, 147, 230, 165, 158, 123, 202, 134, 75, 147, 144, 189, 145, 97, 139, 202, 138, 58, 88, 168, 161, 149, 180, 161, 137, 144, 153, 222, 146, 134, 146, 137, 140, 146, 72, 183, 143, 230, 144, 138, 165, 79, 133, 204, 111, 149, 164, 143, 142, 143, 138, 114, 233, 142, 185, 153, 131, 139, 147, 122, 134, 136, 131, 156, 140, 131, 221, 143, 143, 179, 152, 162, 147, 119, 123, 111, 195, 147, 149, 206, 182, 147, 124, 132, 144, 169, 125, 168, 182, 100, 184, 222, 143, 122, 152, 160, 121, 150, 131, 229, 123, 161, 195, 134, 140, 149, 124, 208, 124, 178, 133, 136, 143, 137, 189, 136, 140, 219, 122, 198, 205, 144, 135, 173, 197, 141, 150, 194, 62, 130, 143, 121, 174, 128, 161, 124, 181, 167, 128, 129, 130, 143, 150, 193, 130, 146, 183, 136, 226, 133, 141, 136, 136, 147, 142, 109, 149, 152, 189, 213, 192, 138, 156, 156, 141, 176, 135, 140, 129, 90, 168, 161, 206, 136, 172, 198, 147, 199, 152, 172, 158, 160, 142, 120, 190, 167, 128, 166, 185, 178, 105, 140, 238, 131, 148, 248, 166, 84, 153, 143, 217, 132, 159, 199, 84, 156, 183, 112, 130, 135, 189, 198, 155, 147, 200, 143, 124, 206, 83, 197, 146, 143, 130, 147, 139, 184, 73, 184, 150, 132, 139, 221, 148, 141, 95, 236, 109, 136, 140, 227, 95, 189, 127, 145, 247, 122, 140, 166, 137, 197, 145, 236, 130, 219, 200, 136, 140, 147, 174, 76, 127, 152, 201, 138, 130, 171, 178, 119, 156, 153, 240, 211, 144, 124, 167, 211, 145, 118, 130, 217, 215, 137, 146, 135, 116, 159, 125, 104, 143, 179, 133, 218, 210, 184, 148, 151, 186, 140, 141, 204, 146, 193, 143, 187, 143, 191, 96, 239, 242, 158, 153, 132, 158, 68, 112, 161, 174, 240, 200, 170, 99, 153, 144, 138, 180, 165, 173, 120, 114, 113, 137, 130, 161, 141, 140, 183, 139, 99, 214, 147, 144, 166, 185, 186, 149, 158, 197, 175, 141, 169, 149, 208, 141, 231, 167, 122, 168, 142, 126, 57, 240, 171, 146, 187, 193, 153, 130, 137, 122, 146, 132, 125, 148, 201, 136, 127, 139, 198, 209, 154, 209, 205, 131, 130, 131, 209, 156, 188, 127, 136, 128, 125, 141, 144, 217, 128, 136, 194, 140, 127, 189, 131, 149, 127, 131, 153, 145, 192, 135, 167, 213, 149, 127, 152, 140, 203, 130, 155, 146, 192, 213, 140, 121, 202, 146, 181, 132, 147, 176, 144, 133, 146, 149, 152, 175, 131, 167, 153, 195, 232, 151, 156, 136, 140, 112, 134, 140, 197, 137, 144, 141, 136, 135, 150, 167, 142, 135, 146, 154, 137, 230, 129, 156, 137, 239, 220, 191, 134, 177, 151, 176, 138, 164, 138, 143, 142, 121, 138, 169, 141, 147, 139, 164, 148, 88, 160, 171, 209, 139, 189, 228, 221, 139, 192, 140, 143, 205, 147, 236, 140, 197, 145, 146, 162, 211, 161, 136, 132, 65, 68, 146, 139, 190, 175, 155, 142, 142, 176, 220, 160, 137, 150, 141, 143, 224, 169, 130, 144, 244, 154, 95, 134, 138, 141, 177, 131, 137, 183, 235, 164, 219, 152, 139, 221, 139, 194, 159, 217, 189, 146, 198, 158, 144, 164, 145, 134, 215, 145, 165, 162, 187, 146, 141, 225, 150, 209, 135, 142, 149, 140, 146, 156, 140, 120, 233, 145, 139, 106, 141, 75, 179, 145, 173, 111, 144, 163, 129, 152, 227, 204, 143, 158, 141, 117, 142, 202, 138, 210, 144, 136, 157, 236, 142, 204, 181, 164, 167, 135, 194, 149, 148, 230, 133, 151, 225, 229, 148, 120, 154, 215, 142, 209, 199, 137, 119, 143, 216, 145, 142, 145, 211, 121, 185, 134, 245, 137, 214, 121, 122, 167, 165, 232, 121, 152, 173, 143, 144, 118, 137, 140, 158, 144, 149, 242, 169, 229, 140] [163.73, 128.43, 47.17, 111.94, 38.77, 118.08, 176.12, 38.49, 115.35, 112.54, 52.81, 45.0, 42.9, 165.02, 41.91, 128.43, 155.83, 125.98, 44.17, 159.86, 105.08, 96.6, 44.0, 148.29, 120.89, 88.61, 51.62, 115.66, 44.15, 161.5, 168.78, 159.52, 46.46, 158.92, 50.26, 105.94, 112.96, 158.95, 42.0, 150.07, 39.96, 162.28, 146.42, 45.25, 42.44, 159.26, 33.58, 32.52, 60.35, 156.07, 111.19, 47.49, 116.93, 51.38, 131.87, 157.56, 98.86, 31.24, 48.1, 52.77, 65.8, 110.04, 43.94, 124.95, 51.0, 45.26, 44.79, 144.86, 52.21, 56.75, 43.95, 84.79, 42.44, 38.53, 32.93, 41.31, 18.17, 84.81, 49.15, 29.28, 40.28, 42.72, 39.31, 155.65, 42.53, 135.03, 52.3, 149.94, 108.17, 84.28, 87.84, 48.71, 46.92, 41.94, 122.74, 119.44, 115.64, 29.05, 47.32, 40.83, 65.25, 41.47, 68.82, 50.82, 37.39, 51.64, 46.37, 39.66, 128.56, 57.5, 66.8, 74.45, 50.64, 74.23, 141.26, 72.02, 75.02, 119.39, 78.82, 43.33, 101.97, 128.73, 60.27, 159.12, 162.51, 50.18, 149.24, 114.91, 162.4, 160.48, 160.77, 62.28, 154.65, 149.26, 9.42, 169.43, 159.92, 164.28, 62.56, 151.97, 158.64, 151.4, 153.0, 151.42, 131.37, 33.67, 140.21, 168.02, 153.69, 68.85, 144.96, 123.12, 157.17, 138.76, 149.57, 122.26, 125.71, 155.54, 157.5, 148.13, 152.73, 127.39, 116.66, 148.9, 105.53, 135.24, 110.24, 162.61, 165.86, 151.68, 54.46, 96.57, 132.14, 119.18, 152.4, 119.45, 107.05, 167.17, 145.99, 116.73, 143.38, 33.39, 151.57, 155.83, 137.92, 148.35, 166.84, 154.8, 148.01, 62.88, 141.11, 46.81, 140.52, 25.24, 33.77, 172.09, 99.78, 41.59, 165.93, 154.95, 133.09, 76.26, 106.64, 100.55, 53.6, 95.6, 164.56, 112.6, 162.7, 139.17, 61.92, 153.05, 88.81, 159.66, 125.18, 107.51, 137.01, 60.98, 84.75, 100.4, 116.85, 115.68, 154.35, 102.03, 135.17, 114.36, 103.67, 167.62, 104.46, 165.57, 54.48, 66.36, 116.83, 110.22, 152.77, 100.74, 151.04, 102.33, 162.44, 98.13, 145.54, 115.78, 155.17, 66.75, 67.05, 126.4, 95.29, 106.4, 153.26, 146.33, 105.37, 146.5, 168.39, 162.85, 87.45, 94.02, 76.61, 150.63, 149.38, 102.81, 130.47, 167.61, 73.73, 90.52, 135.96, 161.41, 99.25, 153.41, 153.83, 43.37, 51.64, 105.09, 141.02, 142.28, 55.83, 102.93, 126.28, 150.94, 68.18, 48.39, 164.23, 99.75, 94.59, 92.36, 160.6, 142.11, 145.79, 90.82, 102.27, 101.44, 72.87, 83.99, 57.0, 137.75, 99.99, 155.45, 83.48, 26.6, 170.5, 139.98, 181.74, 91.31, 14.0, 67.6, 163.92, 162.44, 92.86, 70.47, 156.82, 143.76, 26.6, 100.4, 97.82, 139.42, 64.54, 154.95, 56.58, 163.8, 102.2, 108.47, 133.75, 120.79, 125.36, 114.08, 161.79, 147.74, 66.7, 91.27, 116.55, 146.41, 150.37, 101.34, 113.63, 133.44, 130.44, 107.97, 110.25, 108.52, 129.25, 130.4, 131.54, 85.36, 100.76, 140.24, 165.06, 112.54, 99.13, 170.73, 128.1, 142.33, 159.04, 169.91, 109.24, 138.08, 101.34, 110.38, 151.32, 117.63, 85.49, 114.66, 160.24, 158.75, 147.28, 95.84, 36.0, 95.62, 51.03, 143.77, 66.65, 120.99, 31.95, 64.25, 170.05, 122.73, 84.87, 128.13, 113.04, 133.04, 114.45, 71.38, 125.54, 104.12, 130.46, 101.74, 90.15, 153.72, 109.22, 63.11, 68.06, 169.63, 129.46, 147.11, 135.43, 110.46, 111.16, 152.92, 105.89, 101.78, 142.47, 106.33, 164.25, 140.5, 110.74, 117.94, 111.44, 120.98, 169.46, 145.41, 32.64, 132.59, 110.54, 133.92, 102.89, 118.25, 135.68, 104.21, 93.8, 110.72, 91.0, 137.63, 172.54, 9.05, 135.18, 140.52, 34.19, 101.36, 65.75, 118.17, 103.61, 52.95, 99.62, 127.51, 33.19, 34.17, 97.95, 145.16, 100.96, 99.78, 96.83, 35.88, 106.02, 129.85, 105.91, 56.74, 108.4, 81.41, 107.73, 146.39, 56.38, 103.02, 46.1, 104.6, 142.89, 93.38, 55.95, 96.86, 94.3, 164.98, 51.9, 117.78, 96.45, 154.74, 146.81, 34.1, 149.23, 166.81, 100.04, 138.1, 151.77, 105.03, 52.73, 123.98, 141.06, 105.23, 156.88, 94.92, 145.59, 113.12, 101.42, 171.02, 100.59, 164.38, 150.1, 122.65, 107.41, 93.28, 99.42, 107.27, 98.07, 54.92, 97.59, 140.31, 140.96, 136.19, 40.72, 95.56, 100.88, 108.21, 97.74, 146.58, 135.28, 91.21, 102.0, 183.11, 103.69, 29.87, 153.81, 41.82, 92.41, 76.0, 109.15, 135.2, 104.44, 173.37, 160.42, 95.26, 127.84, 85.57, 106.52, 38.82, 142.94, 104.92, 147.22, 154.21, 53.44, 164.95, 92.62, 112.12, 107.99, 108.92, 163.47, 107.5, 99.38, 157.14, 164.24, 96.02, 107.38, 136.55, 98.1, 111.08, 92.88, 82.65, 88.24, 91.91, 170.39, 29.42, 101.33, 52.95, 103.84, 163.11, 90.62, 149.63, 94.9, 102.01, 147.84, 81.21, 140.3, 28.47, 130.44, 115.13, 95.64, 105.47, 146.41, 79.52, 135.53, 89.01, 110.53, 79.05, 133.02, 95.82, 142.32, 139.91, 102.92, 102.83, 136.63, 160.44, 32.65, 93.48, 110.15, 169.42, 68.39, 102.64, 95.76, 148.17, 78.15, 145.75, 112.13, 164.4, 107.6, 73.07, 99.83, 37.32, 157.11, 149.7, 109.91, 144.23, 92.43, 125.58, 91.61, 106.04, 107.87, 96.44, 108.41, 99.28, 164.68, 134.15, 125.8, 100.02, 99.11, 141.72, 136.14, 106.26, 133.74, 96.67, 65.45, 104.36, 136.45, 107.74, 98.29, 172.12, 94.94, 157.89, 74.33, 156.17, 93.31, 108.07, 144.68, 100.79, 106.97, 102.81, 160.13, 138.94, 104.83, 94.15, 140.41, 109.72, 95.47, 137.9, 110.7, 138.16, 93.77, 178.97, 103.65, 101.69, 31.32, 132.82, 91.83, 102.71, 138.55, 92.96, 129.8, 103.22, 57.83, 96.93, 140.12, 92.21, 99.7, 181.07, 146.68, 147.2, 106.68, 91.45, 168.67, 104.36, 167.29, 95.41, 144.69, 101.16, 103.49, 153.45, 153.99, 101.91, 96.68, 163.78, 98.57, 120.53, 104.6, 145.64, 111.94, 95.96, 177.68, 44.07, 92.73, 121.0, 102.32, 145.55, 147.83, 96.32, 103.19, 177.55, 159.17, 106.08, 148.72, 109.04, 150.68, 108.02, 157.22, 42.94, 103.8, 165.28, 107.29, 145.97, 124.68, 170.97, 104.59, 119.05, 150.46, 133.18, 164.54, 109.32, 117.67, 108.49, 146.49, 140.6, 49.66, 91.83, 138.26, 162.79, 128.49, 133.26, 109.88, 141.82, 95.23, 106.57, 115.25, 177.77, 108.77, 123.21, 101.09, 145.59, 141.55, 143.11, 92.7, 80.32, 165.61, 134.65, 105.65, 96.19, 148.18, 95.66, 145.45, 64.91, 109.08, 141.58, 164.39, 98.86, 131.2, 72.83, 163.24, 100.46, 140.14, 98.62, 147.54, 21.19, 160.9, 99.45, 100.53, 168.69, 102.83, 160.59, 69.16, 56.73, 103.17, 95.25, 171.67, 100.84, 147.45, 146.96, 152.82, 79.72, 100.25, 95.34, 146.75, 176.03, 100.3, 151.97, 44.71, 89.97, 117.62, 161.19, 98.23, 108.36, 64.56, 97.53, 160.82, 176.78, 102.71, 121.95, 164.44, 165.42, 93.67, 166.97, 148.18, 93.63, 148.69, 87.05, 100.42, 114.8, 123.8, 108.16, 135.94, 130.02, 58.46, 176.62, 80.22, 120.48, 109.08, 76.48, 156.02, 146.27, 108.22, 60.02, 102.62, 153.29, 101.59, 155.7, 97.0, 134.37, 176.38, 177.34, 111.54, 95.96, 44.42, 179.53, 108.53, 133.62, 172.57, 104.36, 95.93, 155.18, 132.04, 163.05, 80.58, 173.12, 52.81, 92.68, 91.83, 121.3, 69.48, 152.26, 180.2, 156.75, 91.79, 138.58, 151.82, 63.63, 142.8, 94.11, 148.37, 46.82, 175.73, 34.15, 101.56, 141.47, 50.36, 133.05, 152.91, 95.02, 171.86, 124.71, 98.52, 161.76, 82.44, 131.53, 182.25, 87.28, 136.49, 119.41, 34.23, 90.57, 133.35, 133.63, 131.55, 85.07, 162.72, 107.84, 96.06, 92.31, 170.59, 24.64, 124.77, 165.3, 96.63, 87.85, 165.05, 112.4, 123.52, 182.82, 128.54, 97.3, 127.11, 162.2, 49.28, 91.68, 99.69, 94.6, 157.66, 62.66, 66.98, 66.92, 115.99, 98.31, 100.5, 175.84, 91.11, 98.21, 103.06, 117.81, 130.66, 81.41, 123.79, 145.59, 143.36, 101.1, 90.0, 105.54, 136.67, 88.72, 139.14, 140.65, 105.5, 106.47, 103.66, 154.86, 106.61, 161.69, 124.92, 96.03, 123.41, 102.83, 173.95, 112.22, 101.39, 101.82, 124.48, 141.15, 163.53, 149.44, 92.95, 101.35, 177.03, 138.78, 111.0, 111.08, 149.71, 94.25, 51.36, 136.87, 152.94, 107.6, 141.06, 114.89, 126.81, 114.04, 67.81, 112.91, 181.52, 109.39, 102.83, 170.93, 96.83, 164.36, 111.66, 99.24, 108.61, 129.09, 121.6, 157.64, 145.3, 164.98, 124.22, 131.83, 109.31, 140.64, 159.45, 145.07, 103.06, 102.79, 121.59, 111.25, 172.36, 119.19, 101.63, 123.67, 107.86, 165.29, 101.7, 97.37, 119.79, 110.17, 113.99, 83.37, 49.03, 85.2, 134.21, 99.83, 178.98, 132.45, 153.94, 141.19, 72.79, 124.96, 110.65, 105.62, 107.18, 165.94, 109.88, 156.43, 97.83, 164.71, 62.36, 170.73, 99.27, 80.02, 105.47, 165.76, 111.09, 128.01, 109.84, 58.83, 142.6, 143.22, 93.29, 104.18, 64.83, 104.93, 92.0, 128.71, 149.31, 110.41, 76.0, 105.71, 102.24, 114.98, 151.04, 175.49, 83.59, 61.43, 107.35, 96.21, 129.67, 155.27, 74.94, 96.69, 152.87, 130.34, 140.15, 114.0, 61.92, 101.11, 130.85, 108.14, 151.98, 113.16, 127.21, 111.84, 158.68, 147.65, 103.55, 155.48, 120.99, 149.76, 104.22, 104.32, 114.05, 93.97, 106.97, 145.73, 123.8, 154.52, 146.84, 110.65, 112.95, 144.91, 99.64, 113.97, 131.27, 169.04, 142.17, 113.5, 101.03, 39.59, 150.47, 114.07, 98.63, 176.47, 105.56, 29.24, 92.32, 150.0, 106.99, 166.87, 164.16, 166.8, 104.53, 148.38, 132.35, 156.2, 107.99, 106.0, 148.06, 104.81, 68.57, 153.97, 112.56, 108.34, 159.63, 120.98, 151.74, 28.82, 125.32, 118.61, 67.74, 100.83, 143.14, 148.89, 102.34, 52.65, 106.43, 133.75, 126.27, 105.06, 96.35, 105.26, 148.37, 113.37, 106.18, 156.89, 155.45, 152.05, 103.25, 165.32, 113.5, 107.84, 38.04, 101.3, 148.27, 50.64, 154.82, 169.7, 117.42, 98.98, 162.96, 93.94, 122.96, 105.03, 96.8, 142.95, 99.92, 110.44, 125.47, 33.85, 104.82, 39.04, 51.02, 135.66, 96.86, 166.8, 145.95, 106.38, 108.9, 157.96, 96.81, 146.05, 168.05, 162.91, 62.87, 92.49, 79.82, 107.47, 158.28, 60.58, 118.48, 108.5, 139.54, 161.22, 101.38, 108.48, 148.64, 109.54, 98.79, 62.19, 171.41, 109.43, 179.98, 170.18, 126.14, 110.89, 95.61, 132.76, 111.65, 109.16, 33.6, 123.68, 46.57, 151.84, 46.85, 101.04, 113.58, 116.46, 168.25, 104.95, 99.13, 117.61, 155.2, 113.89, 53.47, 144.23, 70.74, 160.54, 98.76, 159.97, 111.28, 116.38, 119.18, 138.68, 85.63, 81.5, 114.6, 95.93, 123.43, 108.52, 42.79, 101.95, 109.95, 101.73, 3.22, 96.86, 61.04, 141.56, 110.09, 125.94, 40.88, 132.62, 130.38, 125.48, 171.64, 107.14, 118.51, 113.54, 63.65, 76.45, 109.18, 102.71, 94.69, 106.38, 84.82, 107.45, 122.37, 146.51, 98.69, 102.74, 117.84, 126.21, 90.12, 92.6, 159.22, 49.21, 126.61, 67.82, 160.18, 107.24, 157.75, 129.57, 111.52, 74.47, 143.91, 105.96, 108.7

In [156]:
l.extend(maxmissile)

In [157]:
print(l)

[217.0, 180.0, 50.0, 157.0, 50.0, 162.0, 236.0, 46.0, 177.0, 177.0, 62.0, 45.0, 48.0, 221.0, 53.0, 209.0, 211.0, 171.0, 50.0, 225.0, 138.0, 120.0, 98.0, 194.0, 149.0, 118.0, 55.0, 188.0, 83.0, 228.0, 223.0, 210.0, 57.0, 223.0, 79.0, 143.0, 160.0, 221.0, 45.0, 199.0, 94.0, 224.0, 218.0, 47.0, 53.0, 221.0, 77.0, 38.0, 73.0, 210.0, 139.0, 52.0, 173.0, 64.0, 178.0, 160.0, 115.0, 66.0, 51.0, 64.0, 71.0, 160.0, 69.0, 170.0, 64.0, 78.0, 125.0, 198.0, 103.0, 57.0, 59.0, 104.0, 56.0, 48.0, 34.0, 49.0, 30.0, 108.0, 57.0, 42.0, 57.0, 49.0, 42.0, 198.0, 48.0, 204.0, 63.0, 157.0, 143.0, 100.0, 107.0, 54.0, 48.0, 44.0, 187.0, 158.0, 163.0, 35.0, 149.0, 53.0, 66.0, 59.0, 71.0, 57.0, 40.0, 59.0, 53.0, 73.0, 194.0, 69.0, 67.0, 75.0, 60.0, 75.0, 155.0, 78.0, 82.0, 165.0, 82.0, 53.0, 120.0, 194.0, 63.0, 212.0, 207.0, 63.0, 210.0, 183.0, 210.0, 223.0, 209.0, 73.0, 216.0, 191.0, 11.0, 227.0, 227.0, 234.0, 64.0, 202.0, 210.0, 196.0, 219.0, 208.0, 153.0, 42.0, 184.0, 239.0, 213.0, 74.0, 191.0, 169.0, 213.0, 193.0, 212.0, 190.0, 151.0, 205.0, 234.0, 212.0, 214.0, 165.0, 144.0, 204.0, 159.0, 176.0, 141.0, 219.0, 205.0, 205.0, 55.0, 141.0, 199.0, 192.0, 180.0, 184.0, 137.0, 221.0, 213.0, 170.0, 200.0, 37.0, 178.0, 196.0, 193.0, 220.0, 216.0, 217.0, 219.0, 75.0, 216.0, 65.0, 192.0, 28.0, 34.0, 217.0, 143.0, 85.0, 206.0, 210.0, 169.0, 94.0, 136.0, 119.0, 67.0, 129.0, 213.0, 153.0, 219.0, 187.0, 75.0, 213.0, 121.0, 220.0, 173.0, 170.0, 199.0, 74.0, 88.0, 149.0, 145.0, 153.0, 210.0, 117.0, 192.0, 141.0, 146.0, 202.0, 141.0, 209.0, 64.0, 69.0, 156.0, 142.0, 187.0, 139.0, 194.0, 178.0, 228.0, 132.0, 189.0, 162.0, 232.0, 69.0, 87.0, 163.0, 163.0, 145.0, 190.0, 222.0, 147.0, 202.0, 218.0, 229.0, 146.0, 117.0, 83.0, 192.0, 210.0, 139.0, 186.0, 214.0, 82.0, 116.0, 191.0, 216.0, 158.0, 206.0, 199.0, 47.0, 60.0, 168.0, 204.0, 182.0, 59.0, 157.0, 149.0, 194.0, 79.0, 83.0, 216.0, 159.0, 99.0, 142.0, 220.0, 188.0, 199.0, 98.0, 160.0, 149.0, 74.0, 131.0, 64.0, 183.0, 142.0, 194.0, 129.0, 42.0, 227.0, 189.0, 190.0, 135.0, 23.0, 75.0, 224.0, 237.0, 102.0, 78.0, 197.0, 168.0, 58.0, 166.0, 121.0, 189.0, 73.0, 205.0, 69.0, 175.0, 156.0, 125.0, 176.0, 155.0, 170.0, 148.0, 184.0, 196.0, 80.0, 141.0, 150.0, 187.0, 191.0, 123.0, 140.0, 175.0, 181.0, 131.0, 132.0, 143.0, 159.0, 178.0, 138.0, 87.0, 146.0, 151.0, 237.0, 152.0, 141.0, 224.0, 163.0, 143.0, 166.0, 224.0, 170.0, 152.0, 152.0, 150.0, 195.0, 135.0, 145.0, 143.0, 196.0, 196.0, 187.0, 115.0, 47.0, 125.0, 68.0, 196.0, 87.0, 146.0, 41.0, 68.0, 235.0, 148.0, 109.0, 170.0, 155.0, 161.0, 149.0, 96.0, 157.0, 137.0, 171.0, 148.0, 129.0, 200.0, 143.0, 70.0, 72.0, 216.0, 170.0, 178.0, 162.0, 140.0, 136.0, 199.0, 151.0, 139.0, 188.0, 143.0, 243.0, 189.0, 142.0, 167.0, 148.0, 157.0, 225.0, 209.0, 44.0, 161.0, 140.0, 189.0, 145.0, 202.0, 177.0, 136.0, 153.0, 154.0, 145.0, 180.0, 229.0, 12.0, 181.0, 191.0, 69.0, 172.0, 82.0, 160.0, 143.0, 67.0, 122.0, 193.0, 40.0, 35.0, 124.0, 192.0, 130.0, 137.0, 147.0, 39.0, 150.0, 166.0, 128.0, 66.0, 155.0, 186.0, 144.0, 178.0, 81.0, 138.0, 94.0, 135.0, 177.0, 144.0, 143.0, 132.0, 160.0, 236.0, 55.0, 146.0, 147.0, 200.0, 183.0, 37.0, 204.0, 226.0, 130.0, 174.0, 206.0, 148.0, 67.0, 151.0, 193.0, 150.0, 202.0, 117.0, 188.0, 144.0, 164.0, 233.0, 161.0, 200.0, 195.0, 158.0, 142.0, 145.0, 126.0, 135.0, 121.0, 56.0, 142.0, 213.0, 191.0, 173.0, 46.0, 149.0, 129.0, 142.0, 127.0, 194.0, 162.0, 128.0, 146.0, 253.0, 133.0, 38.0, 183.0, 42.0, 136.0, 102.0, 134.0, 216.0, 136.0, 234.0, 194.0, 128.0, 171.0, 110.0, 130.0, 43.0, 187.0, 116.0, 192.0, 192.0, 60.0, 214.0, 134.0, 122.0, 125.0, 161.0, 211.0, 138.0, 132.0, 212.0, 220.0, 138.0, 139.0, 172.0, 136.0, 146.0, 93.0, 105.0, 129.0, 125.0, 220.0, 37.0, 132.0, 66.0, 163.0, 226.0, 139.0, 205.0, 138.0, 141.0, 178.0, 119.0, 195.0, 42.0, 163.0, 154.0, 146.0, 138.0, 189.0, 94.0, 177.0, 139.0, 138.0, 84.0, 174.0, 134.0, 153.0, 191.0, 153.0, 135.0, 166.0, 207.0, 42.0, 140.0, 140.0, 230.0, 69.0, 140.0, 135.0, 195.0, 119.0, 186.0, 149.0, 208.0, 134.0, 98.0, 137.0, 60.0, 217.0, 187.0, 138.0, 171.0, 120.0, 151.0, 158.0, 127.0, 147.0, 137.0, 152.0, 112.0, 220.0, 173.0, 158.0, 122.0, 137.0, 180.0, 175.0, 154.0, 164.0, 141.0, 74.0, 150.0, 176.0, 140.0, 140.0, 233.0, 134.0, 212.0, 114.0, 191.0, 116.0, 138.0, 198.0, 154.0, 138.0, 144.0, 198.0, 196.0, 130.0, 139.0, 167.0, 133.0, 139.0, 154.0, 153.0, 186.0, 138.0, 240.0, 126.0, 153.0, 33.0, 138.0, 140.0, 131.0, 175.0, 144.0, 180.0, 139.0, 79.0, 138.0, 177.0, 139.0, 130.0, 225.0, 192.0, 223.0, 146.0, 139.0, 234.0, 147.0, 232.0, 137.0, 190.0, 142.0, 136.0, 196.0, 169.0, 152.0, 124.0, 213.0, 135.0, 162.0, 138.0, 179.0, 142.0, 126.0, 243.0, 55.0, 116.0, 155.0, 135.0, 199.0, 190.0, 124.0, 130.0, 243.0, 233.0, 133.0, 205.0, 121.0, 199.0, 135.0, 205.0, 53.0, 130.0, 202.0, 137.0, 189.0, 163.0, 218.0, 139.0, 143.0, 215.0, 182.0, 211.0, 133.0, 197.0, 138.0, 203.0, 175.0, 73.0, 125.0, 196.0, 198.0, 168.0, 192.0, 136.0, 177.0, 134.0, 135.0, 205.0, 240.0, 130.0, 166.0, 135.0, 168.0, 204.0, 186.0, 140.0, 90.0, 212.0, 191.0, 134.0, 135.0, 196.0, 104.0, 211.0, 67.0, 110.0, 183.0, 214.0, 123.0, 174.0, 107.0, 201.0, 136.0, 176.0, 125.0, 201.0, 23.0, 200.0, 127.0, 139.0, 234.0, 137.0, 201.0, 92.0, 62.0, 135.0, 113.0, 233.0, 148.0, 226.0, 192.0, 164.0, 114.0, 130.0, 137.0, 200.0, 230.0, 136.0, 183.0, 57.0, 142.0, 148.0, 200.0, 139.0, 150.0, 68.0, 154.0, 166.0, 230.0, 160.0, 150.0, 225.0, 209.0, 96.0, 173.0, 196.0, 133.0, 229.0, 111.0, 139.0, 150.0, 159.0, 142.0, 172.0, 158.0, 72.0, 230.0, 125.0, 145.0, 153.0, 101.0, 229.0, 197.0, 156.0, 88.0, 147.0, 208.0, 132.0, 216.0, 151.0, 192.0, 230.0, 229.0, 144.0, 152.0, 61.0, 235.0, 134.0, 172.0, 232.0, 194.0, 168.0, 220.0, 191.0, 236.0, 85.0, 189.0, 58.0, 126.0, 135.0, 156.0, 70.0, 209.0, 253.0, 241.0, 143.0, 186.0, 212.0, 72.0, 173.0, 136.0, 202.0, 50.0, 228.0, 37.0, 142.0, 175.0, 51.0, 214.0, 199.0, 142.0, 243.0, 167.0, 158.0, 242.0, 95.0, 196.0, 249.0, 141.0, 142.0, 162.0, 47.0, 93.0, 164.0, 176.0, 149.0, 118.0, 235.0, 131.0, 135.0, 151.0, 218.0, 49.0, 182.0, 237.0, 142.0, 141.0, 239.0, 127.0, 129.0, 247.0, 192.0, 126.0, 164.0, 234.0, 62.0, 145.0, 134.0, 121.0, 214.0, 66.0, 71.0, 80.0, 166.0, 130.0, 127.0, 236.0, 141.0, 132.0, 131.0, 140.0, 158.0, 122.0, 168.0, 213.0, 199.0, 141.0, 98.0, 126.0, 176.0, 124.0, 157.0, 218.0, 156.0, 134.0, 151.0, 210.0, 129.0, 198.0, 150.0, 163.0, 148.0, 156.0, 236.0, 161.0, 155.0, 129.0, 147.0, 161.0, 215.0, 156.0, 135.0, 139.0, 251.0, 200.0, 155.0, 163.0, 215.0, 129.0, 68.0, 147.0, 214.0, 133.0, 160.0, 141.0, 146.0, 154.0, 78.0, 150.0, 249.0, 156.0, 140.0, 248.0, 118.0, 204.0, 141.0, 135.0, 154.0, 172.0, 127.0, 226.0, 168.0, 212.0, 136.0, 146.0, 127.0, 167.0, 189.0, 207.0, 166.0, 149.0, 143.0, 143.0, 233.0, 155.0, 146.0, 167.0, 156.0, 206.0, 137.0, 138.0, 144.0, 144.0, 157.0, 101.0, 69.0, 91.0, 162.0, 144.0, 235.0, 142.0, 191.0, 185.0, 102.0, 133.0, 150.0, 135.0, 142.0, 244.0, 138.0, 212.0, 140.0, 216.0, 78.0, 234.0, 103.0, 95.0, 138.0, 186.0, 140.0, 173.0, 134.0, 60.0, 161.0, 197.0, 129.0, 139.0, 65.0, 159.0, 92.0, 186.0, 213.0, 142.0, 76.0, 112.0, 137.0, 147.0, 199.0, 245.0, 109.0, 76.0, 160.0, 135.0, 149.0, 193.0, 80.0, 139.0, 209.0, 204.0, 150.0, 157.0, 68.0, 135.0, 163.0, 156.0, 236.0, 154.0, 134.0, 161.0, 202.0, 212.0, 145.0, 211.0, 147.0, 207.0, 141.0, 135.0, 142.0, 169.0, 156.0, 224.0, 189.0, 193.0, 189.0, 150.0, 146.0, 200.0, 135.0, 155.0, 195.0, 218.0, 185.0, 153.0, 147.0, 53.0, 198.0, 150.0, 151.0, 245.0, 147.0, 30.0, 122.0, 208.0, 141.0, 234.0, 209.0, 226.0, 146.0, 199.0, 185.0, 236.0, 145.0, 150.0, 195.0, 140.0, 72.0, 204.0, 145.0, 153.0, 209.0, 166.0, 217.0, 36.0, 158.0, 158.0, 69.0, 131.0, 214.0, 196.0, 133.0, 68.0, 150.0, 166.0, 163.0, 146.0, 131.0, 138.0, 191.0, 149.0, 144.0, 213.0, 211.0, 210.0, 127.0, 170.0, 141.0, 154.0, 47.0, 131.0, 202.0, 54.0, 217.0, 223.0, 185.0, 139.0, 218.0, 137.0, 164.0, 144.0, 121.0, 245.0, 148.0, 140.0, 177.0, 34.0, 150.0, 49.0, 58.0, 199.0, 128.0, 221.0, 207.0, 149.0, 150.0, 208.0, 123.0, 214.0, 242.0, 231.0, 77.0, 120.0, 118.0, 135.0, 217.0, 76.0, 161.0, 146.0, 170.0, 239.0, 133.0, 164.0, 204.0, 153.0, 133.0, 72.0, 221.0, 161.0, 240.0, 249.0, 131.0, 144.0, 132.0, 146.0, 165.0, 127.0, 44.0, 163.0, 52.0, 199.0, 49.0, 161.0, 147.0, 158.0, 245.0, 149.0, 156.0, 148.0, 211.0, 175.0, 61.0, 175.0, 73.0, 204.0, 158.0, 204.0, 151.0, 170.0, 162.0, 180.0, 120.0, 89.0, 154.0, 151.0, 160.0, 146.0, 66.0, 137.0, 148.0, 139.0, 12.0, 105.0, 72.0, 187.0, 156.0, 184.0, 48.0, 173.0, 182.0, 174.0, 231.0, 139.0, 165.0, 141.0, 65.0, 108.0, 156.0, 154.0, 103.0, 157.0, 100.0, 155.0, 159.0, 175.0, 132.0, 170.0, 140.0, 161.0, 159.0, 160.0, 214.0, 62.0, 167.0, 72.0, 212.0, 148.0, 211.0, 172.0, 152.0, 90.0, 187.0, 146.0, 151.0, 188.0, 154.0, 87.0, 210.0, 161.0, 221.0, 200.0, 143.0, 42.0, 189.0, 52.0, 228.0, 207.0, 134.0, 150.0, 211.0, 115.0, 51.0, 136.0, 154.0, 159.0, 130.0, 108.0, 225.0, 175.0, 234.0, 150.0, 164.0, 148.0, 111.0, 132.0, 224.0, 132.0, 141.0, 128.0, 227.0, 147.0, 199.0, 94.0, 145.0, 163.0, 150.0, 216.0, 157.0, 134.0, 135.0, 116.0, 231.0, 189.0, 118.0, 200.0, 129.0, 146.0, 130.0, 246.0, 160.0, 104.0, 145.0, 136.0, 153.0, 203.0, 107.0, 219.0, 143.0, 197.0, 206.0, 235.0, 139.0, 154.0, 73.0, 193.0, 156.0, 73.0, 230.0, 133.0, 184.0, 169.0, 235.0, 55.0, 138.0, 140.0, 92.0, 133.0, 237.0, 74.0, 132.0, 152.0, 190.0, 40.0, 149.0, 97.0, 205.0, 240.0, 126.0, 180.0, 242.0, 111.0, 148.0, 175.0, 242.0, 147.0, 186.0, 152.0, 142.0, 141.0, 213.0, 234.0, 148.0, 196.0, 199.0, 127.0, 159.0, 142.0, 149.0, 131.0, 182.0, 202.0, 209.0, 139.0, 179.0, 123.0, 128.0, 197.0, 126.0, 201.0, 161.0, 219.0, 128.0, 157.0, 182.0, 164.0, 144.0, 187.0, 144.0, 147.0, 186.0, 195.0, 143.0, 149.0, 168.0, 127.0, 144.0, 178.0, 152.0, 93.0, 181.0, 144.0, 197.0, 96.0, 161.0, 166.0, 150.0, 143.0, 215.0, 69.0, 92.0, 123.0, 142.0, 163.0, 141.0, 136.0, 155.0, 87.0, 133.0, 172.0, 131.0, 151.0, 142.0, 87.0, 142.0, 139.0, 143.0, 52.0, 155.0, 191.0, 69.0, 90.0, 86.0, 162.0, 210.0, 151.0, 158.0, 138.0, 197.0, 177.0, 175.0, 161.0, 134.0, 145.0, 165.0, 150.0, 139.0, 187.0, 216.0, 146.0, 122.0, 149.0, 161.0, 146.0, 144.0, 79.0, 145.0, 164.0, 215.0, 147.0, 230.0, 165.0, 158.0, 123.0, 202.0, 134.0, 75.0, 147.0, 144.0, 189.0, 145.0, 97.0, 139.0, 202.0, 138.0, 58.0, 88.0, 168.0, 161.0, 149.0, 180.0, 161.0, 137.0, 144.0, 153.0, 222.0, 146.0, 134.0, 146.0, 137.0, 140.0, 146.0, 72.0, 183.0, 143.0, 230.0, 144.0, 138.0, 165.0, 79.0, 133.0, 204.0, 111.0, 149.0, 164.0, 143.0, 142.0, 143.0, 138.0, 114.0, 233.0, 142.0, 185.0, 153.0, 131.0, 139.0, 147.0, 122.0, 134.0, 136.0, 131.0, 156.0, 140.0, 131.0, 221.0, 143.0, 143.0, 179.0, 152.0, 162.0, 147.0, 119.0, 123.0, 111.0, 195.0, 147.0, 149.0, 206.0, 182.0, 147.0, 124.0, 132.0, 144.0, 169.0, 125.0, 168.0, 182.0, 100.0, 184.0, 222.0, 143.0, 122.0, 152.0, 160.0, 121.0, 150.0, 131.0, 229.0, 123.0, 161.0, 195.0, 134.0, 140.0, 149.0, 124.0, 208.0, 124.0, 178.0, 133.0, 136.0, 143.0, 137.0, 189.0, 136.0, 140.0, 219.0, 122.0, 198.0, 205.0, 144.0, 135.0, 173.0, 197.0, 141.0, 150.0, 194.0, 62.0, 130.0, 143.0, 121.0, 174.0, 128.0, 161.0, 124.0, 181.0, 167.0, 128.0, 129.0, 130.0, 143.0, 150.0, 193.0, 130.0, 146.0, 183.0, 136.0, 226.0, 133.0, 141.0, 136.0, 136.0, 147.0, 142.0, 109.0, 149.0, 152.0, 189.0, 213.0, 192.0, 138.0, 156.0, 156.0, 141.0, 176.0, 135.0, 140.0, 129.0, 90.0, 168.0, 161.0, 206.0, 136.0, 172.0, 198.0, 147.0, 199.0, 152.0, 172.0, 158.0, 160.0, 142.0, 120.0, 190.0, 167.0, 128.0, 166.0, 185.0, 178.0, 105.0, 140.0, 238.0, 131.0, 148.0, 248.0, 166.0, 84.0, 153.0, 143.0, 217.0, 132.0, 159.0, 199.0, 84.0, 156.0, 183.0, 112.0, 130.0, 135.0, 189.0, 198.0, 155.0, 147.0, 200.0, 143.0, 124.0, 206.0, 83.0, 197.0, 146.0, 143.0, 130.0, 147.0, 139.0, 184.0, 73.0, 184.0, 150.0, 132.0, 139.0, 221.0, 148.0, 141.0, 95.0, 236.0, 109.0, 136.0, 140.0, 227.0, 95.0, 189.0, 127.0, 145.0, 247.0, 122.0, 140.0, 166.0, 137.0, 197.0, 145.0, 236.0, 130.0, 219.0, 200.0, 136.0, 140.0, 147.0, 174.0, 76.0, 127.0, 152.0, 201.0, 138.0, 130.0, 171.0, 178.0, 119.0, 156.0, 153.0, 240.0, 211.0, 144.0, 124.0, 167.0, 211.0, 145.0, 118.0, 130.0, 217.0, 215.0, 137.0, 146.0, 135.0, 116.0, 159.0, 125.0, 104.0, 143.0, 179.0, 133.0, 218.0, 210.0, 184.0, 148.0, 151.0, 186.0, 140.0, 141.0, 204.0, 146.0, 193.0, 143.0, 187.0, 143.0, 191.0, 96.0, 239.0, 242.0, 158.0, 153.0, 132.0, 158.0, 68.0, 112.0, 161.0, 174.0, 240.0, 200.0, 170.0, 99.0, 153.0, 144.0, 138.0, 180.0, 165.0, 173.0, 120.0, 114.0, 113.0, 137.0, 130.0, 161.0, 141.0, 140.0, 183.0, 139.0, 99.0, 214.0, 147.0, 144.0, 166.0, 185.0, 186.0, 149.0, 158.0, 197.0, 175.0, 141.0, 169.0, 149.0, 208.0, 141.0, 231.0, 167.0, 122.0, 168.0, 142.0, 126.0, 57.0, 240.0, 171.0, 146.0, 187.0, 193.0, 153.0, 130.0, 137.0, 122.0, 146.0, 132.0, 125.0, 148.0, 201.0, 136.0, 127.0, 139.0, 198.0, 209.0, 154.0, 209.0, 205.0, 131.0, 130.0, 131.0, 209.0, 156.0, 188.0, 127.0, 136.0, 128.0, 125.0, 141.0, 144.0, 217.0, 128.0, 136.0, 194.0, 140.0, 127.0, 189.0, 131.0, 149.0, 127.0, 131.0, 153.0, 145.0, 192.0, 135.0, 167.0, 213.0, 149.0, 127.0, 152.0, 140.0, 203.0, 130.0, 155.0, 146.0, 192.0, 213.0, 140.0, 121.0, 202.0, 146.0, 181.0, 132.0, 147.0, 176.0, 144.0, 133.0, 146.0, 149.0, 152.0, 175.0, 131.0, 167.0, 153.0, 195.0, 232.0, 151.0, 156.0, 136.0, 140.0, 112.0, 134.0, 140.0, 197.0, 137.0, 144.0, 141.0, 136.0, 135.0, 150.0, 167.0, 142.0, 135.0, 146.0, 154.0, 137.0, 230.0, 129.0, 156.0, 137.0, 239.0, 220.0, 191.0, 134.0, 177.0, 151.0, 176.0, 138.0, 164.0, 138.0, 143.0, 142.0, 121.0, 138.0, 169.0, 141.0, 147.0, 139.0, 164.0, 148.0, 88.0, 160.0, 171.0, 209.0, 139.0, 189.0, 228.0, 221.0, 139.0, 192.0, 140.0, 143.0, 205.0, 147.0, 236.0, 140.0, 197.0, 145.0, 146.0, 162.0, 211.0, 161.0, 136.0, 132.0, 65.0, 68.0, 146.0, 139.0, 190.0, 175.0, 155.0, 142.0, 142.0, 176.0, 220.0, 160.0, 137.0, 150.0, 141.0, 143.0, 224.0, 169.0, 130.0, 144.0, 244.0, 154.0, 95.0, 134.0, 138.0, 141.0, 177.0, 131.0, 137.0, 183.0, 235.0, 164.0, 219.0, 152.0, 139.0, 221.0, 139.0, 194.0, 159.0, 217.0, 189.0, 146.0, 198.0, 158.0, 144.0, 164.0, 145.0, 134.0, 215.0, 145.0, 165.0, 162.0, 187.0, 146.0, 141.0, 225.0, 150.0, 209.0, 135.0, 142.0, 149.0, 140.0, 146.0, 156.0, 140.0, 120.0, 233.0, 145.0, 139.0, 106.0, 141.0, 75.0, 179.0, 145.0, 173.0, 111.0, 144.0, 163.0, 129.0, 152.0, 227.0, 204.0, 143.0, 158.0, 141.0, 117.0, 142.0, 202.0, 138.0, 210.0, 144.0, 136.0, 157.0, 236.0, 142.0, 204.0, 181.0, 164.0, 167.0, 135.0, 194.0, 149.0, 148.0, 230.0, 133.0, 151.0, 225.0, 229.0, 148.0, 120.0, 154.0, 215.0, 142.0, 209.0, 199.0, 137.0, 119.0, 143.0, 216.0, 145.0, 142.0, 145.0, 211.0, 121.0, 185.0, 134.0, 245.0, 137.0, 214.0, 121.0, 122.0, 167.0, 165.0, 232.0, 121.0, 152.0, 173.0, 143.0, 144.0, 118.0, 137.0, 140.0, 158.0, 144.0, 149.0, 242.0, 169.0, 229.0, 140.0, 5356.075, 5104.498, 5251.579000000001, 4859.402, 5174.293, 5457.408, 5112.976, 5061.005, 4994.225, 5854.736999999999, 5091.685, 5132.889, 5133.170999999999, 5355.335, 5047.401, 5276.22, 5022.814, 5456.561, 5311.198, 5288.481, 4898.392, 4821.249, 5169.358, 4654.4929999999995, 5466.726, 4899.566, 4855.332, 4908.017, 5388.911, 4896.4259999999995, 5037.059, 5715.955, 5453.843000000001, 5472.656, 4895.8820000000005, 4807.975, 4934.859, 5776.464, 5166.9490000000005, 4932.353, 5334.213000000001, 5022.97, 5343.735, 5166.965999999999, 4931.483, 5431.456, 5551.979, 4810.337, 5629.359, 5274.055, 5380.085, 4914.499, 5436.919, 5405.111, 5448.616, 5109.867, 5308.991999999999, 5569.045, 4872.303, 5253.133000000001, 5029.194, 5045.075, 5982.108, 5674.779, 5325.404, 4833.6759999999995, 5133.723, 4967.76, 5224.697, 5538.111, 5600.196999999999, 4979.384, 4842.096, 5250.811, 4870.104, 4929.485, 5372.384, 4945.791, 5217.83, 5577.308000000001, 4876.4, 5647.448, 4795.2, 5109.39, 5113.465999999999, 4984.016, 5307.9169999999995, 4622.169, 4812.18, 5634.149, 5637.931, 5514.24, 4919.464, 5349.326999999999, 5627.8240000000005, 4840.687, 5134.412, 5605.854, 4864.246, 5007.943, 5235.861, 5079.077, 5361.353, 4580.35, 5211.134, 5694.315, 5562.253000000001, 4780.093, 5517.185, 5398.358, 5225.184, 4652.366, 5834.9490000000005, 4638.509, 5352.9580000000005, 5725.108, 4929.155, 5096.396, 5715.281, 4911.9, 5319.1230000000005, 5805.13, 5292.411, 5698.975, 4697.744000000001, 5369.757, 4839.4929999999995, 5448.168000000001, 5125.49, 5906.556, 5460.422, 5453.235, 5378.696, 5797.985, 4811.64, 4894.638, 5279.183000000001, 4660.056, 5064.545, 5330.298000000001, 5076.652, 5515.8, 5456.175, 5286.425, 5083.524, 5284.509, 5199.749, 4981.738, 5113.104, 5226.557, 5396.804, 5800.271, 4539.424, 5642.7919999999995, 5149.447, 5111.4929999999995, 5141.6140000000005, 5035.106, 5700.713000000001, 5098.562, 4953.125, 4986.427, 4943.682, 5169.779, 5134.721, 5310.344, 5208.015, 5449.116999999999, 5162.099, 5259.335, 5113.842000000001, 5004.475, 4958.42, 5400.84, 5052.284000000001, 5354.938, 5029.978, 5220.318, 5108.52, 5136.438, 5251.596, 5154.767, 4819.377, 5034.791, 5161.512, 4997.59, 5159.005999999999, 4844.832, 5434.0380000000005, 5038.521, 5421.389, 4974.075, 5597.195, 5152.276, 5913.227, 4499.207, 4845.503, 4873.622, 6006.066, 5118.302, 5500.273, 4998.103, 4838.48, 4954.837, 4860.59, 5556.869000000001, 5182.255999999999, 5052.112, 5245.685, 5240.787, 4853.897, 5498.281, 5170.9490000000005, 5068.87, 4890.905, 5566.068, 5720.155, 5048.008, 5005.13, 5187.281, 5295.451999999999, 5088.745, 5001.19, 4889.684, 5575.471, 5327.166, 4649.835999999999, 5612.6990000000005, 4789.205, 4655.084, 4855.589, 5249.649, 5263.170999999999, 5296.596, 5288.3769999999995, 4806.825, 4945.712, 5376.293000000001, 5002.798, 5258.483, 4824.938, 5276.85, 4756.74, 5212.829000000001, 5068.276, 4644.774, 5019.62, 4612.669, 5153.919, 5474.861999999999, 5495.116999999999, 5651.361, 5238.354, 5148.306, 5444.7609999999995, 4764.608, 5469.665, 5518.4580000000005, 5401.78, 5124.552, 5409.8009999999995, 5028.91, 4957.624, 5420.891, 5516.812, 5588.113, 5003.0509999999995, 4944.904, 5091.366, 5392.25, 5136.577, 5160.486, 5036.135, 5366.4, 4986.714, 5042.222, 5677.156999999999, 5625.2, 5131.715, 5297.773, 5355.249, 5470.3730000000005, 4898.049, 5008.692, 5006.418, 5585.804, 4818.582, 5631.1140000000005, 4746.646, 5154.476, 4816.652, 4930.512, 5249.706, 4878.343, 5135.365, 5255.979, 5199.508, 5484.54, 5126.626, 4693.715999999999, 5014.7390000000005, 5903.766, 4973.1359999999995, 5676.491, 4795.363, 4660.129, 4866.95, 5341.616, 5496.541, 4922.951, 5094.269, 4756.851, 5161.278, 5714.509, 4786.128, 5245.603, 4700.677, 5604.109, 5385.409000000001, 5578.934, 5383.8369999999995, 5222.492, 4508.93, 5629.052, 4654.48, 5123.1720000000005, 5177.311, 5626.036999999999, 5258.651, 5612.531, 5326.901999999999, 5259.659000000001, 5559.5509999999995, 5517.438, 5058.2, 4982.919, 5138.005999999999, 4898.009, 5349.422, 4842.608, 4932.604, 5183.8009999999995, 5523.996999999999, 4940.758, 5159.854, 5547.99, 4793.177, 4837.48, 5274.015, 5032.247, 4886.005, 5304.911999999999, 5220.258, 5305.765, 5225.545999999999, 5418.679, 5221.888, 5612.549, 5440.058000000001, 5022.714, 4747.808, 5672.686, 5328.705, 5657.151999999999, 5302.88, 4560.866, 5449.78, 5167.58, 5467.3330000000005, 5663.928000000001, 5979.102, 5290.834, 5088.982, 5067.647, 4895.945, 5053.616, 4543.9259999999995, 5609.226, 5314.416, 5111.255999999999, 5103.427, 5025.608, 5314.26, 5538.18, 5527.475, 5116.826, 5432.391, 4690.439, 5626.232, 5654.009, 4907.456, 5402.4130000000005, 5685.5869999999995, 5670.276999999999, 4986.929, 5529.691999999999, 5196.59, 5144.667, 5383.731, 5591.169, 4754.59, 5583.771, 5362.347, 5553.0380000000005, 4795.332, 5028.303, 4636.8859999999995, 5348.268, 5563.715999999999, 5130.181, 5285.3640000000005, 5286.656999999999, 5010.869000000001, 4899.384, 4845.947, 5347.179, 5096.254, 5041.928, 4670.644, 5644.669, 5822.615, 4981.29, 4805.46, 5216.204000000001, 5060.127, 5178.42, 5574.946, 5507.528, 5092.212, 5367.133000000001, 4823.2970000000005, 5133.432, 5434.781, 5932.726, 4799.9220000000005, 5026.454000000001, 4946.516, 4915.15, 5417.72, 4621.702, 5411.743, 4805.022, 4991.485, 5075.705, 5427.718000000001, 4703.95, 5311.441, 5569.306, 5101.5779999999995, 4875.38, 5039.432, 5653.335, 5207.471, 5308.021

In [158]:
dfy = pd.DataFrame()

In [159]:
dfy['Max Velocity'] = l

In [160]:
dfy

      Max Velocity
0          217.000
1          180.000
2           50.000
3          157.000
4           50.000
...            ...
4124      5125.694
4125      5124.001
4126      5224.924
4127      4395.850
4128      4965.060

[4129 rows x 1 columns]

In [162]:
l2.extend(avgmissile)

In [163]:
dfy['Avg Velocity'] = l2

In [166]:
dfy.to_csv('CombinedMissileAndPlane.csv')

In [34]:
import pandas as pd
dff = pd.read_csv('CombinedMissileAndPlane.csv')

In [4]:
dff

      Unnamed: 0  Max Velocity  Avg Velocity
0              0       217.000        163.73
1              1       180.000        128.43
2              2        50.000         47.17
3              3       157.000        111.94
4              4        50.000         38.77
...          ...           ...           ...
4124        4124      5125.694       4648.23
4125        4125      5124.001       4762.00
4126        4126      5224.924       4629.42
4127        4127      4395.850       4139.46
4128        4128      4965.060       4413.09

[4129 rows x 3 columns]

In [9]:
dfff = pd.read_csv('dropdataset.csv')

In [15]:
dfff

      Plane Number  Latitude   Longitude   Altitude   Velocity       Time
0               _0   52.65885    13.35933  998.50960   50.69159   1.038638
1               _0  105.08950    24.71907  993.86300   50.94687   2.095138
2               _0  155.54170    35.65016  986.41090   51.35468   3.100146
3               _0  205.00450    46.36698  976.26680   51.90525   4.100414
4               _0  254.46740    57.08380  963.31270   52.60038   5.102814
...            ...        ...         ...        ...        ...        ...
38995         _999  484.51100   438.93720  309.43540   68.72480  22.175140
38996         _999  506.57600   458.76260  244.43110   71.33197  23.181670
38997         _999  528.20730   478.19920  177.86330   73.90663  24.184190
38998         _999  549.83810   497.63590  108.48560   76.49785  25.192470
38999         _999  571.46900   517.07250   36.29804   79.10401  26.193140

[39000 rows x 6 columns]

In [17]:
dfff.columns

Index(['Plane Number', 'Latitude ', 'Longitude ', 'Altitude ', 'Velocity ',
       'Time '],
      dtype='object')

In [21]:
dfff['Velocity ']

0        50.69159
1        50.94687
2        51.35468
3        51.90525
4        52.60038
           ...
38995    68.72480
38996    71.33197
38997    73.90663
38998    76.49785
38999    79.10401
Name: Velocity , Length: 39000, dtype: float64

In [39]:
avgdrop = []
maxdrop = []
v = 0
v1 = 0
cnt = 0
temp = ""
for index, row in dfff.iterrows():
    if row['Plane Number'] != temp:
        if cnt != 0: 
            avgdrop.append((round(v/cnt, 2)))
            maxdrop.append(v1)
        cnt = 1
        v = row['Velocity ']
        v1 = row['Velocity ']
        temp = row['Plane Number']
    else: 
        cnt += 1
        v += row['Velocity ']
        temp = row['Plane Number']
        v1 = max(v1, row['Velocity '])
        
        
avgdrop.append(round(v/cnt, 2))
maxdrop.append(v1)

In [40]:
len(avgdrop)

1500

In [41]:
len(maxdrop)

1500

In [42]:
dff

      Unnamed: 0  Max Velocity  Avg Velocity
0              0       217.000        163.73
1              1       180.000        128.43
2              2        50.000         47.17
3              3       157.000        111.94
4              4        50.000         38.77
...          ...           ...           ...
4124        4124      5125.694       4648.23
4125        4125      5124.001       4762.00
4126        4126      5224.924       4629.42
4127        4127      4395.850       4139.46
4128        4128      4965.060       4413.09

[4129 rows x 3 columns]

In [31]:
xx=[]
xx=dff['Max Velocity']
xx

0        217.000
1        180.000
2         50.000
3        157.000
4         50.000
          ...
4124    5125.694
4125    5124.001
4126    5224.924
4127    4395.850
4128    4965.060
Name: Max Velocity, Length: 4129, dtype: float64

In [43]:
dfg = pd.DataFrame() 
dfg['Max Velocity'] = maxdrop
dfg['Avg Velocity'] = avgdrop

In [44]:
dfg

      Max Velocity  Avg Velocity
0         89.29247         65.79
1         79.14204         50.18
2         75.52921         43.28
3         87.03955         62.58
4         73.65965         38.63
...            ...           ...
1495      74.20048         40.18
1496      93.72268         71.85
1497      88.70041         64.95
1498      82.13162         55.15
1499      79.10401         50.11

[1500 rows x 2 columns]

In [45]:
dff = dff[['Max Velocity','Avg Velocity']]

In [49]:
dff = dff.append(dfg)

In [51]:
dff.to_csv('FinalCombinedClusterring.csv')

In [73]:
airaltdrop = []
#maxdrop = []
v = 0
v1 = 0
cnt = 0
sumi = 0
temp = ""
for index, row in df1.iterrows():
    if row['Plane Number'] != temp:
        if cnt != 0: 
            airaltdrop.append(round(sumi/cnt, 2))
          #  maxdrop.append(v1)
        cnt = 1
        temp = row['Plane Number']
    else: 
        cnt += 1
        temp = row['Plane Number']
        sumi += row['Altitude ']

airaltdrop.append(round(sumi/cnt, 2))
#maxdrop.append(v1)

In [74]:
dropaltdrop = []
#maxdrop = []
v = 0
v1 = 0
cnt = 0
sumi = 0
temp = ""
for index, row in dfff.iterrows():
    if row['Plane Number'] != temp:
        if cnt != 0: 
            dropaltdrop.append(round(sumi/cnt, 2))
          #  maxdrop.append(v1)
        cnt = 1
        temp = row['Plane Number']
    else: 
        cnt += 1
        temp = row['Plane Number']
        sumi += row['Altitude ']

dropaltdrop.append(round(sumi/cnt, 2))
#maxdrop.append(v1)

In [75]:
missilealtdrop = []
#maxdrop = []
v = 0
v1 = 0
cnt = 0
sumi = 0
temp = ""
for index, row in df4.iterrows():
    if row['Plane Number'] != temp:
        if cnt != 0: 
            missilealtdrop.append(round(sumi/cnt, 2))
          #  maxdrop.append(v1)
        cnt = 1
        temp = row['Plane Number']
    else: 
        cnt += 1
        temp = row['Plane Number']
        sumi += row['Altitude']

missilealtdrop.append(round(sumi/cnt, 2))
#maxdrop.append(v1)

In [77]:
len(airaltdrop)

2129

In [78]:
len(dropaltdrop)

1500

In [79]:
len(missilealtdrop)

2000

In [90]:
lf = []
lf.extend(airaltdrop)

In [93]:
lf.extend(missilealtdrop)

In [94]:
len(lf)

4129

In [95]:
lf.extend(dropaltdrop)

In [96]:
len(lf)

5629

In [97]:
dff['Avg Altitude Drop'] = lf

In [100]:
dff.to_csv('FinalClusterringAvgAlt.csv')

In [127]:
airaltdropp = []
#maxdrop = []
v = 0
v1 = 0
cnt = 0
sumi = 0
temp = ""
temp2 = 0
for index, row in df1.iterrows():
    if row['Plane Number'] != temp:
        if cnt != 0: 
            airaltdropp.append(round(sumi, 2))
          #  maxdrop.append(v1)
        cnt = 1
        temp = row['Plane Number']
    else: 
        cnt += 1
        sumi = (row['Altitude '] - temp2)
        temp = row['Plane Number']
        temp2 = row['Altitude ']

airaltdropp.append(round(sumi, 2))
#maxdrop.append(v1)

In [128]:
dropaltdropp = []
#maxdrop = []
v = 0
v1 = 0
cnt = 0
sumi = 0
temp = ""
temp2 = 0
for index, row in dfff.iterrows():
    if row['Plane Number'] != temp:
        if cnt != 0: 
            dropaltdropp.append(round(sumi, 2))
          #  maxdrop.append(v1)
        cnt = 1
        temp = row['Plane Number']
    else: 
        cnt += 1
        sumi = (row['Altitude '] - temp2)
        temp = row['Plane Number']
        temp2 = row['Altitude ']

dropaltdropp.append(round(sumi, 2))
#maxdrop.append(v1)

In [129]:
missilealtdropp = []
#maxdrop = []
v = 0
v1 = 0
cnt = 0
sumi = 0
temp = 0
temp2  = 0
for index, row in df4.iterrows():
    if row['Plane Number'] != temp:
        if cnt != 0: 
            missilealtdropp.append(round(sumi, 2))
          #  maxdrop.append(v1)
        cnt = 1
        temp = row['Plane Number']
    else: 
        cnt += 1
        sumi = (row['Altitude'] - temp2)
        temp = row['Plane Number']
        temp2 = row['Altitude']


missilealtdropp.append(round(sumi, 2))
#maxdrop.append(v1)

In [132]:
lff = []
lff.extend(airaltdropp)

In [133]:
lff.extend(missilealtdropp)

In [134]:
lff.extend(dropaltdropp)

In [136]:
len(lff)

5629

In [137]:
dff['DropAlt'] = lff

In [139]:
dff.to_csv('finalclusterr.csv')

In [144]:
from math import sqrt

In [154]:
#Let Missile Location Coordinates
traj_x = 108
traj_y = 106
traj_z = 105

#Let prediction Location Coordinates
traj1_x = 0
traj1_y = 1
traj1_z = 2

#let Actual Cordinates of Air Object
traj_currx = 9
traj_curry = 8
traj_currz = 12

#Let Velocity of Target Shooting Missile

initial_velocity = 120

distance_x = traj_x - traj1_x
distance_y = traj_y - traj1_y
distance_z = traj_x - traj1_z

theta = math.atan(distance_x / distance_y)
phi = math.atan(distance_z / distance_x)

#Let Acceleration Due To Gravity is
g = 9.8

#Time needed by Object to move at predicted Position

Time_needed = 5

#if (Time_needed_to reach predicted point == Time Needed by MIssile to hit the object) therfore we can shoot at that point of time.

Distance = sqrt((traj1_x - traj_x)**2 + (traj1_y - traj_y)**2 + (traj1_z - traj_z)**2)
print(Distance)   
if abs(Distance - (initial_velocity * math.cos(theta)*math.sin(phi)*Time_needed - (0.5*g*((Time_needed)**2)))) <= 5:
    print("We can shoot")
else:
    print("Wait For the Next Interception")
    print(initial_velocity * math.cos(theta)*math.sin(phi)*Time_needed - (0.5*g*((Time_needed)**2)))

182.47739586041882
Wait For the Next Interception
170.46854621499767